name: Rspec Actions
on: [push, pull_request]
jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: Gemfile
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.4.1
        bundler-cache: true
    - name: Run tests
      run: |
        bundle exec rspec 'tests/run_rubocop.rb'
        bundle exec rspec 'tests/run_foodcritic.rb'
